### ISSUE TITLE
Cant get the Inputs list in HomeKit with Onkyo TX-NR686

### ISSUE THREAD

**Issue by alexsalex** [ToddGreenfield/homebridge-onkyo#71] opened 2020-03-12 05:54 UTC
```
        {
            "name": "Onkyo",
            "receivers": [
                {
                    "name": "Onkyo AVR",
                    "model": "TX-NR636",
                    "ip_address": "10.0.1.7",
                    "default_input": "dvd",
                    "zone": "main",
                    "default_volume": "40",
                    "max_volume": "80",
                    "poll_status_interval": "0",
                    "map_volume_100": false,
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true,
                    "inputs": [
                        {
                            "input_name": "tv",
                            "display_name": "TV"
                        },
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV"
                        },
                        {
                            "input_name": "game",
                            "display_name": "Game"
                        }
                    ]
                }
            ],
            "platform": "Onkyo"
        }
```

And I get only Apple TV option... How to get the TV and Game, and switch between them?

**Comment by alexsalex** [comment] 2020-03-12 06:39
<img width="315" alt="Screen Shot 2020-03-11 at 10 49 13 PM" src="https://user-images.githubusercontent.com/17325366/76494173-88b43100-63f1-11ea-9396-0f7104350138.png">

**Comment by przbrz1987** [comment] 2020-04-16 22:56
Hi there,

i don't know if it helps but i was having similar issue. Try to set filter_inputs to "false" and it will show you all available inputs, then switch between them to find out which is which. In my case "game" input was actually "video3". I belive the problem is both of us are using unsupported receivers (646 here). Try to find model with similar inputs layout to 686 on the supported models list.

My config

`"model": "TX-NR709",
			"ip_address": "xxx.xxx.xxx.xxx",
			"poll_status_interval": "3000",
			"name": "Receiver",
			"zone": "main",
			"default_input": "game",
			"default_volume": "25",
			"max_volume": "45",
			
			"map_volume_100": false,
			"volume_dimmer": true,
			"switch_service": false,
			"filter_inputs": true,
			"inputs": [{
					"input_name": "video3",
					"display_name": "Game"
				},
				{
					"input_name": "video2",
					"display_name": "Shield"
				},
				{
					"input_name": "phono",
					"display_name": "Phono"
				}
			]`

**Comment by solowalker27** [comment] 2020-06-05 16:48
My PR https://github.com/ToddGreenfield/homebridge-onkyo/pull/80 includes a newer eiscp.js that supports many newer models than the previous version. It should explicitly support the TX-NR646 and goes up to the TX-NR676 which is much closer to the 686 and would be good to try to see if it works. You can test the PR or wait until it's merged.

**Comment by alexsalex** [comment] 2020-06-17 22:42
```
        {
            "name": "Onkyo",
            "receivers": [
                {
                    "name": "Onkyo AVR",
                    "model": "TX-NR676",
                    "ip_address": "10.0.1.7",
                    "default_input": "dvd",
                    "zone": "main",
                    "default_volume": "45",
                    "max_volume": "80",
                    "poll_status_interval": "0",
                    "map_volume_100": false,
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true,
                    "inputs": [
                        {
                            "input_name": "tv",
                            "display_name": "TV"
                        },
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV"
                        },
                        {
                            "input_name": "airplay",
                            "display_name": "AirPlay"
                        },
                        {
                            "input_name": "game",
                            "display_name": "Game"
                        }
                    ]
                }
            ],
            "platform": "Onkyo"
        }
```

**Comment by alexsalex** [comment] 2020-06-17 22:46
![IMG_0711](https://user-images.githubusercontent.com/17325366/84958175-a27ca880-b0b1-11ea-8853-7603ca957527.PNG)
![IMG_0712](https://user-images.githubusercontent.com/17325366/84958176-a4466c00-b0b1-11ea-952d-1c274ad0672c.PNG)

**Comment by solowalker27** [comment] 2020-06-18 01:28
Can you attach your logs?

**Comment by solowalker27** [comment] 2020-06-18 01:29
Also, what happens when you set `filter_inputs` to false?

**Comment by jondthompson** [comment] 2020-12-21 15:30
I believe there should be a "better way" to handle inputs in general to make it more user friendly.  I'm not sure if the plugin can affect the config files (or preferably if homebridge/homebridge UI could allow reading/writing of a second config file), but it would be good to poll the device for inputs, then switch between them and question the user on what they're using a particular input for or if they're using it at all. (I also wish manufacturers would stop hard coding this and just give us input numbers)

Or, it seems that the devices store the names we define. Can we just get those?

**Comment by rs-pille** [comment] 2021-01-31 10:48
Do you think, there is a chance, to switch to a Tune-in Radio preset via homebridge? I want to create a morning-routine scene: turn on my Onkyo TX-NR656, choose Net-Input, choose Tune-In Radio, choose favourite station

**Comment by wtdeane** [comment] 2021-03-11 19:03
For the NR686, I set the value for the filter inputs to false so I got a complete listing of all the inputs that the receiver polled back to me.  Then I simply went through each one in the home app, noting if it changed the input on the receiver.  My config now looks like this: 

[
    {
        "model": "TX-NR636",
        "ip_address": "192.168.0.153",
        "poll_status_interval": "3000",
        "name": "Receiver",
        "zone": "main",
        "default_input": "net",
        "default_volume": "40",
        "max_volume": "70",
        "map_volume_100": false,
        "inputs": [
            {
                "input_name": "dvd",
                "display_name": "BD/DVD"
            },
            {
                "input_name": "video2",
                "display_name": "CBL/SAT"
            },
            {
                "input_name": "video4",
                "display_name": "AUX"
            },
            {
                "input_name": "video6",
                "display_name": "Apple TV"
            },
            {
                "input_name": "video3",
                "display_name": "Game"
            },
            {
                "input_name": "CD",
                "display_name": "CD"
            },
            {
                "input_name": "TV",
                "display_name": "TV"
            },
            {
                "input_name": "phone",
                "display_name": "Phono"
            },
            {
                "input_name": "TUNER",
                "display_name": "TUNER"
            },
            {
                "input_name": "network",
                "display_name": "NET"
            },
            {
                "input_name": "bluetooth",
                "display_name": "BLUETOOTH"
            }
        ],
        "volume_dimmer": false,
        "switch_service": false,
        "filter_inputs": true
    }
]


I hope this helps someone.

**Closed** 2021-04-07 15:14 UTC
Labels: bug
