### ISSUE TITLE
Error Initialising Platform

### ISSUE THREAD

**Issue by Hazza42** [ToddGreenfield/homebridge-onkyo#45] opened 2020-02-19 04:13 UTC
Upon installing I get this error when rebooting Homebridge:

`[2/19/2020, 4:02:01 AM] [Onkyo] Initializing Onkyo platform...
[2/19/2020, 4:02:01 AM] TypeError: Cannot read property 'forEach' of undefined
    at new OnkyoAccessory (/usr/local/lib/node_modules/homebridge-onkyo/index.js:72:22)
    at receivers.forEach.receiver (/usr/local/lib/node_modules/homebridge-onkyo/index.js:36:22)
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/usr/local/lib/node_modules/homebridge-onkyo/index.js:35:13)
    at new OnkyoPlatform (/usr/local/lib/node_modules/homebridge-onkyo/index.js:28:8)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[2/19/2020, 4:02:01 AM] Got SIGTERM, shutting down Homebridge...`

I use Homebridge Config UI so I let that modify my config.json (below)
Is there something wrong with my config or is there a bug with homebridge-onkyo?

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:20",
        "port": 12345,
        "pin": "123-45-678"
    },
    "accessories": [
        {
            "accessory": "Smartglass",
            "name": "Xbox",
            "liveid": "FD00B10BB08F55CC",
            "consoleip": "10.0.0.42"
        },
        {
            "accessory": "WeMo",
            "name": "Fan",
            "description": "Bedroom Fan",
            "wemo_name": "Fan"
        },
        {
            "accessory": "WeMo",
            "name": "Horse Light",
            "description": "Living Room Horse Light",
            "wemo_name": "Horse Light"
        },
        {
            "accessory": "WeMo",
            "name": "Christmas Lights",
            "description": "Bedroom Christmas Lights",
            "wemo_name": "Fairy Lights"
        },
        {
            "accessory": "SkyQ",
            "name": "Sky Q",
            "ipAddress": "10.0.0.118"
        },
        {
            "name": "Living Room TV",
            "ip": "10.0.0.250",
            "mac": "C4:36:6C:A5:30:D2",
            "keyFile": "",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Apple TV"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Sky"
                }
            ],
            "notificationButtons": [
                "Motion Detected: Garden",
                "Motion Detected: Garage"
            ],
            "infoButtonAction": "INFO",
            "accessory": "webostv"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "tempUnits": "c",
            "sudo": true,
            "debug": false,
            "log": {
                "method": "file",
                "path": "/Users/Hazza/.homebridge/homebridge.log"
            },
            "platform": "config"
        },
        {
            "name": "Harmony Hub",
            "hubIP": "10.0.0.57",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": true,
            "TVAccessory": true,
            "mainActivity": "Play Xbox",
            "platform": "HarmonyHubWebSocket"
        },
        {
            "name": "Onkyo",
            "receivers": [
                {
                    "name": "Onkyo AVR",
                    "model": "TX-L50",
                    "ip_address": "10.0.0.221",
                    "default_input": "net",
                    "default_volume": "10",
                    "max_volume": "35",
                    "poll_status_interval": "0",
                    "map_volume_100": true,
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": false
                }
            ],
            "platform": "Onkyo"
        }
    ]
}

**Comment by tonesto7** [comment] 2020-02-21 18:55
I'm pretty sure it's because the developer is trying to write to a const `array_inputs`

**Comment by solowalker27** [comment] 2020-02-23 00:02
Can you check which version of the plugin you have? I'm trying to match your stack trace to the code and it's not lining up. You can also try to update to the latest version.

**Comment by solowalker27** [comment] 2020-02-23 00:18
Nevermind, I got it matched up now. Investigating.

**Comment by Hazza42** [comment] 2020-02-23 00:27
> Nevermind, I got it matched up now. Investigating.

Cheers, let me know if you need anything else for me! (I am running the latest version fyi)

**Comment by solowalker27** [comment] 2020-02-23 00:41
@cbrandlehner made some changes recently around the inputs handling. Looks like he's expecting `inputs` to be defined, which you don't have. His example in the README.md shows the setup like this:

`"inputs": [
                    {
                        "input_name": "TV",
                        "display_name": "TV"
                    },
                    {
                        "input_name": "AUX",
                        "display_name": "PS4"
                    }
                ]`

Try adding an array of the inputs you want and see if that resolves your problem. Beyond that, @cbrandlehner will have to help you.

**Comment by cbrandlehner** [comment] 2020-02-28 08:16
@Hazza42 this should be fixed with pr #47 
Please reopen if the problem still exists after update to 0.7.8

**Comment by Hazza42** [comment] 2020-02-28 23:48
Thanks, but I’m afraud I’m getting a new error this time:

[2/28/2020, 11:44:48 PM] [Onkyo] Initializing Onkyo platform...
[2/28/2020, 11:44:48 PM] [Onkyo] Configuration does not contain INPUT configuration.
[2/28/2020, 11:44:48 PM] [Onkyo] Continuing without INPUT select options.
[2/28/2020, 11:44:48 PM] SyntaxError: Unexpected token ] in JSON at position 13
    at JSON.parse (<anonymous>)
    at OnkyoAccessory.createRxInput (/usr/local/lib/node_modules/homebridge-onkyo/index.js:236:19)
    at OnkyoAccessory.setUp (/usr/local/lib/node_modules/homebridge-onkyo/index.js:175:8)
    at new OnkyoAccessory (/usr/local/lib/node_modules/homebridge-onkyo/index.js:171:8)
    at receivers.forEach.receiver (/usr/local/lib/node_modules/homebridge-onkyo/index.js:36:22)
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/usr/local/lib/node_modules/homebridge-onkyo/index.js:35:13)
    at new OnkyoPlatform (/usr/local/lib/node_modules/homebridge-onkyo/index.js:28:8)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[2/28/2020, 11:44:48 PM] Got SIGTERM, shutting down Homebridge...

**Comment by cbrandlehner** [comment] 2020-02-29 08:49
too bad :-/

**Comment by cbrandlehner** [comment] 2020-02-29 09:07
@Hazza42 your log does not show the version number of the plugin.
As I am missing a debug line in the log - can you please double check the version you are using?

**Comment by cbrandlehner** [comment] 2020-02-29 09:48
@Hazza42 
I uploaded a new version 0.7.16.
With debug enabled it will create a log like this. I also fixed a problem with reading the configuration.

```
[2/29/2020, 10:41:04 AM] [Onkyo] Initializing Onkyo platform...
[2/29/2020, 10:41:04 AM] [Onkyo] Creating 1 receivers...
[2/29/2020, 10:41:04 AM] [Onkyo] **************************************************************
[2/29/2020, 10:41:04 AM] [Onkyo]   homebridge-onkyo version 0.7.15
[2/29/2020, 10:41:04 AM] [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
[2/29/2020, 10:41:04 AM] [Onkyo] **************************************************************
[2/29/2020, 10:41:04 AM] [Onkyo] start success...
[2/29/2020, 10:41:04 AM] [Onkyo] Debug mode enabled
[2/29/2020, 10:41:04 AM] [Onkyo] name Onkyo Stereo
[2/29/2020, 10:41:04 AM] [Onkyo] IP 192.168.71.105
[2/29/2020, 10:41:04 AM] [Onkyo] Model TX-NR609
[2/29/2020, 10:41:04 AM] [Onkyo] Zone main
[2/29/2020, 10:41:04 AM] [Onkyo] volume_dimmer: true
[2/29/2020, 10:41:04 AM] [Onkyo] filter_inputs: true
[2/29/2020, 10:41:04 AM] [Onkyo] Configuration contains an INPUTS object.
[2/29/2020, 10:41:04 AM] [Onkyo] This is the list of INPUTS after converting from an object into an array: { fm: 'fm' }
[2/29/2020, 10:41:04 AM] [Onkyo] Input filtering is finally true
[2/29/2020, 10:41:04 AM] [Onkyo] poll_status_interval: 0
```

**Comment by Hazza42** [comment] 2020-02-29 11:19
@cbrandlehner 
Updated to 0.7.16, not sure how to enable debug mode, but this is the new log created:

[2/29/2020, 11:13:55 AM] [Onkyo] Initializing Onkyo platform...
[2/29/2020, 11:13:55 AM] [Onkyo] **************************************************************
[2/29/2020, 11:13:55 AM] [Onkyo]   homebridge-onkyo version 0.7.16
[2/29/2020, 11:13:55 AM] [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
[2/29/2020, 11:13:55 AM] [Onkyo] **************************************************************
[2/29/2020, 11:13:55 AM] [Onkyo] start success...
[2/29/2020, 11:13:55 AM] [Onkyo] Configuration does not contain proper INPUTS configuration.
[2/29/2020, 11:13:55 AM] [Onkyo] Continuing without INPUTS filter option.
[2/29/2020, 11:13:55 AM] SyntaxError: Unexpected token ] in JSON at position 13
    at JSON.parse (<anonymous>)
    at OnkyoAccessory.createRxInput (/usr/local/lib/node_modules/homebridge-onkyo/index.js:241:19)
    at OnkyoAccessory.setUp (/usr/local/lib/node_modules/homebridge-onkyo/index.js:180:8)
    at new OnkyoAccessory (/usr/local/lib/node_modules/homebridge-onkyo/index.js:176:8)
    at receivers.forEach.receiver (/usr/local/lib/node_modules/homebridge-onkyo/index.js:36:22)
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/usr/local/lib/node_modules/homebridge-onkyo/index.js:35:13)
    at new OnkyoPlatform (/usr/local/lib/node_modules/homebridge-onkyo/index.js:28:8)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[2/29/2020, 11:13:55 AM] Got SIGTERM, shutting down Homebridge...

**Comment by cbrandlehner** [comment] 2020-02-29 12:09
start homebridge with -D parameter to enable debug.
`homebridge -D`

**Comment by Hazza42** [comment] 2020-03-01 09:37
@cbrandlehner 
Ah cheers, here’s the full debug log:

[3/1/2020, 9:33:13 AM] [Onkyo] Initializing Onkyo platform...
[3/1/2020, 9:33:13 AM] [Onkyo] Creating 1 receivers...
[3/1/2020, 9:33:13 AM] [Onkyo] **************************************************************
[3/1/2020, 9:33:13 AM] [Onkyo]   homebridge-onkyo version 0.7.16
[3/1/2020, 9:33:13 AM] [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
[3/1/2020, 9:33:13 AM] [Onkyo] **************************************************************
[3/1/2020, 9:33:13 AM] [Onkyo] start success...
[3/1/2020, 9:33:13 AM] [Onkyo] Debug mode enabled
[3/1/2020, 9:33:13 AM] [Onkyo] name Onkyo
[3/1/2020, 9:33:13 AM] [Onkyo] IP 10.0.0.221
[3/1/2020, 9:33:13 AM] [Onkyo] Model TX-L50
[3/1/2020, 9:33:13 AM] [Onkyo] Zone main
[3/1/2020, 9:33:13 AM] [Onkyo] volume_dimmer: true
[3/1/2020, 9:33:13 AM] [Onkyo] filter_inputs: false
[3/1/2020, 9:33:13 AM] [Onkyo] Configuration does not contain proper INPUTS configuration.
[3/1/2020, 9:33:13 AM] [Onkyo] Continuing without INPUTS filter option.
[3/1/2020, 9:33:13 AM] [Onkyo] Input filtering is finally false
[3/1/2020, 9:33:13 AM] [Onkyo] poll_status_interval: 0
[3/1/2020, 9:33:13 AM] [Onkyo] defaultInput: net
[3/1/2020, 9:33:13 AM] [Onkyo] defaultVolume: 10
[3/1/2020, 9:33:13 AM] [Onkyo] maxVolume: 35
[3/1/2020, 9:33:13 AM] [Onkyo] mapVolume100: true
[3/1/2020, 9:33:13 AM] [Onkyo] avrSerial: 10.0.0.221
[3/1/2020, 9:33:13 AM] [Onkyo] eventDebug: INFO (connecting) Connecting to 10.0.1.221:60128 (model: TX-L50)
[3/1/2020, 9:33:13 AM] SyntaxError: Unexpected token ] in JSON at position 13
    at JSON.parse (<anonymous>)
    at OnkyoAccessory.createRxInput (/usr/local/lib/node_modules/homebridge-onkyo/index.js:241:19)
    at OnkyoAccessory.setUp (/usr/local/lib/node_modules/homebridge-onkyo/index.js:180:8)
    at new OnkyoAccessory (/usr/local/lib/node_modules/homebridge-onkyo/index.js:176:8)
    at receivers.forEach.receiver (/usr/local/lib/node_modules/homebridge-onkyo/index.js:36:22)
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/usr/local/lib/node_modules/homebridge-onkyo/index.js:35:13)
    at new OnkyoPlatform (/usr/local/lib/node_modules/homebridge-onkyo/index.js:28:8)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[3/1/2020, 9:33:13 AM] Got SIGTERM, shutting down Homebridge...

**Comment by cbrandlehner** [comment] 2020-03-02 19:34
@Hazza42 
This is a duplicate of #55 
TX-L50 is not on the [list of supported Onkyo receivers](https://github.com/ToddGreenfield/homebridge-onkyo/wiki/List-of-supported-Onkyo-receivers)

Thank you for all the problem reports. This really helped improving the code. :-) 
In this case, please check the troubleshooting section of the documentation and read the WIKI.

Closing this issue for now.

**Closed by cbrandlehner** 2020-03-02 19:34 UTC
Labels: bug

**Comment by Hazza42** [comment] 2020-03-03 01:47
No problem!
I don’t suppose the TX-L50 is likely to be supported anytime soon? Sadly I couldn’t get it to work with any of the supported receivers!

**Comment by cbrandlehner** [comment] 2020-03-03 19:56
@Hazza42 
unfortunately we would need a skilled developer, having access to this kind of receiver to test with it, willing to join the project. For me this is beyond what I can contribute.
